//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrier
    {
        public Carrier()
        {
            this.CarrierContacts = new HashSet<CarrierContact>();
        }
    
        public int CarrierId { get; set; }
        public string Name { get; set; }
        public string Abbreviation { get; set; }
        public string Rating { get; set; }
        public int ActiveMonthAssociated { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual ICollection<CarrierContact> CarrierContacts { get; set; }
    }
}
