//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateTaxAudit : TaxAudit
    {
        public string State { get; set; }
        public string Agency { get; set; }
        public Nullable<bool> SalesUseTax { get; set; }
    }
}
