//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxAudit
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public string AuditReason { get; set; }
        public Nullable<decimal> Adjustment { get; set; }
        public string Audtor { get; set; }
    }
}
